version: '3.7'

services:

  frontend:
    image: alberto/frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '80:3000'
    command:
      - npm
      - start

  backend:
    image: alberto/backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '5000:5000'
